version: "3.8"

services:
  ldap:
    image: osixia/openldap:1.3.0
    container_name: example.org
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ADMIN_PASSWORD=JonSn0w
      - LDAP_TLS_VERIFY_CLIENT=try
    command: [--loglevel, trace]

  linux:
    image: rust:1.43.1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust
    environment:
      - LDAP3_ISSUE47_URL=ldaps://example.org
      - CARGO_TARGET_DIR=/tmp/cargo
    volumes:
      - .:/issue47
    working_dir: /issue47
    stdin_open: true
    tty: true
